# Generated by Django 5.0.1 on 2024-01-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(choices=[('Justo Sierra', 'Justo Sierra'), ('Querétaro', 'Querétaro'), ('Tennyson', 'Tennyson'), ('Panteón', 'Panteón'), ('San Sulpicio', 'San Sulpicio'), ('Huerta', 'Huerta'), ('Velatorio', 'Velatorio'), ('Palma', 'Palma'), ('Colegio', 'Colegio'), ('Toledo', 'Toledo'), ('Isla de Agua', 'Isla de Agua'), ('Olivos', 'Olivos')], max_length=20)),
                ('situacion', models.CharField(choices=[('Indicación Ignorada', 'Indicación Ignorada'), ('Consigna no cumplida', 'Consigna no cumplida'), ('Visitante', 'Visitante'), ('Bulto en periferia', 'Bulto en periferia'), ('Bulto en interiores', 'Bulto en interiores'), ('Vehículo en periferia', 'Vehículo en periferia'), ('Manifestaciíon', 'Manifestaciíon'), ('Incendio', 'Incendio')], max_length=40)),
                ('descripcion', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
