# Generated by Django 5.0.1 on 2024-01-29 05:01

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 29, 5, 1, 18, 984653, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
